### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by mshudrak** [google/gcp_scanner#2] opened 2022-06-15 16:23 UTC
Currently, we have one giant scanner [loop](https://github.com/google/gcp_scanner/blob/main/scanner.py#L44) where we launch crawlers from `crawl.py`. We need to split each crawler into individual module that will improve code readability and allow to parallelize the scan. Besides that, we can leverage python classes for the state of execution control, config parsing and enabling/disabling certain functions.

**Comment by sudiptob2** [comment] 2023-02-23 18:50
I can take this issue and do the initial refactoring of the crawler. I have experience in python best practices and the styling guide of `flake8`, `pep8` etc. Besides I have been writing `python` in production for about 2 years now.

Nevertheless, I can always do the necessary research if required and take suggestions from other community members.

**Comment by ggold7046** [comment] 2023-02-27 20:08
Hi @sudiptob2 , @mshudrak , I have basic python knowledge; could I join in this work ? I need guidance though.

**Comment by mshudrak** [comment] 2023-02-28 14:55
Feel free to join :)

**Comment by RahulDubey391** [comment] 2023-02-28 18:21
@mshudrak @ZetaTwo @sudiptob2 Hi, I'll help in creating class designs for code refactoring as well as object pickability for parallelization. Will create an initial PR for review and considerations. Thanks!!!

**Comment by ggold7046** [comment] 2023-03-08 07:04
Hi, Is this work still going on ?

**Comment by aryanagrawal22** [comment] 2023-03-12 09:12
Hi. I am writing to inquire about the status of this issue that I am interested in contributing to as a part of the Google Summer of Code program 2023. Specifically, I am wondering if the issue is still active and if any proposals for it will be considered as I can already see some progress.

**Comment by mshudrak** [comment] 2023-03-13 14:38
Yes, we will consider applications for this issue. It is one of projects listed for GSoC 2023. There is some progress but it requires much more refactoring.

**Comment by ggold7046** [comment] 2023-03-13 19:16
Hi @mshudrak , could you guide about the files where the codes needs to be refactored ; and is there any special suggestions ?

**Comment by sudiptob2** [comment] 2023-03-14 13:54
I have suggested a refactoring strategy in my proposal. If I get selected for GSOC I guess I will be able improve the project's scalability 🙂

**Comment by ggold7046** [comment] 2023-03-14 14:38
> Basically, we want to refactor most of the code in the project. I don't have any special suggestions. You may choose your own refactor strategy in the proposal.

Thanks @mshudrak for your reply. Could you tell me any file which will be easier for me to understand to refactor ? As there are lots of files.

**Comment by Roshan102003** [comment] 2023-03-17 17:28
@mshudrak Can you assign this to me, I can do it no time?

**Comment by mshudrak** [comment] 2023-03-17 17:40
@Roshan102003 we do not assign bugs for individuals now since we have a lot of interest from various contributors. So far, we had multiple PRs to fix this issue. However, this is a long term project requiring coordination with project owners and design doc. I'd prefer to keep it for GSoC 2023 timeframe.

**Closed** 2023-10-21 01:09 UTC
Labels: enhancement, help wanted, refactoring
